### ISSUE TITLE
Gooey Effect broken in Chrome

### ISSUE THREAD

**Issue by NeXTs** [codrops/CreativeGooeyEffects#3]
From all examples only "Loader" works as expected

![gooey](https://cloud.githubusercontent.com/assets/1753208/20173779/6a8c35a6-a743-11e6-8429-f1471b0d50d5.gif)

Probably there are something wrong with svg filter paths.
Related issue https://github.com/codrops/DistortedButtonEffects/issues/3

Chrome 54.0.2840.71 m
Win 10

**Comment by crnacura** [comment]
Thanks a lot for opening the issue, that was it, indeed. I've updated the references to the filters and now it seems to work fine. Let me know if you see the effects correctly now. Thx

**Comment by NeXTs** [comment]
@crnacura Yes it works now, thank you!
